require 'telapi/version'

require 'telapi/error'
require 'telapi/configuration'
require 'telapi/network'

require 'telapi/resource'
require 'telapi/resource_collection'

require 'telapi/account'
require 'telapi/application'
require 'telapi/available_phone_number'
require 'telapi/bna'
require 'telapi/call'
require 'telapi/caller_id'
require 'telapi/carrier'
require 'telapi/conference'
require 'telapi/fraud'
require 'telapi/incoming_phone_number'
require 'telapi/message'
require 'telapi/notification'
require 'telapi/participant'
require 'telapi/recording'
require 'telapi/transcription'
require 'telapi/usage'

require 'telapi/inbound_xml'